---
- name: Install packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ pkgs }}"

- name: AutoStart
  include: autostart.yaml
  tags: autostart

- include: splashscreen.yaml
  tags: splashscreen

- include: silent_boot.yaml
  tags: silent_boot
