---
- name: Check if kernel entry exists
  shell: 'egrep -c "kernel .* {{ entry }}( |$)" "{{ file }}" | cat'
  register: entry_exists

- name: Replace kernel entry
  replace:
    dest: "{{ file }}"
    regexp: '^(kernel .*)$'
    replace: "\\1 {{ entry }}"
  when: entry_exists.stdout == "0"
