---
- name: Remove rainbow square
  lineinfile:
    dest: /boot/config.txt
    regexp: '^disable_splash='
    line: 'disable_splash=1'

- name: Redirect boot messages to tty3
  replace:
    dest: /boot/cmdline.txt
    regexp: 'console=tty1'
    replace: 'console=tty3'

- name: Remove verbose logging at startup
  include: cmdline.yaml entry="{{ item }}" file='/boot/cmdline.txt'
  with_items:
    - splash
    - quiet
    - plymouth.ignore-serial-consoles
    - logo.nologo
    - 'vt.global_cursor_default=0'

- name: Hide login message during auto-login
  lineinfile:
    dest: '/etc/systemd/system/autologin@.service'
    regexp: '^ExecStart='
    line: 'ExecStart=-/sbin/agetty --skip-login --noclear --noissue --login-options "-f {{ pi_user }}" %I $TERM'

- name: Hush login
  copy:
    src: .hushlogin
    dest: "/home/{{ pi_user }}/"
    owner: "{{ pi_user }}"
    group: "{{ pi_user }}"

- name: Suppress kernel messages
  lineinfile:
    dest: /etc/rc.local
    regexp: '^(dmesg .*)$'
    line: 'dmesg --console-off'
    insertbefore: 'exit 0'

- name: Suppress login prompt on console (tty1)
  systemd:
    name: 'getty@tty1.service'
    enabled: no
